export const profiles = [
    {
        id:1,
        pic:"images/1.png",
        pname:"Lene",
        role:"Architect",
        doj:"2019"
    },
    {
        id:2,
        pic:"images/2.png",
        pname:"Tom",
        role:"Architect",
        doj:"2020"
    },
    {
        id:3,
        pic:"images/3.png",
        pname:"Jane",
        role:"Architect",
        doj:"2020"
    },
    {
        id:4,
        pic:"images/4.png",
        pname:"Bob",
        role:"Architect",
        doj:"2024"
    },
    {
        id:5,
        pic:"images/5.png",
        pname:"Ken",
        role:"Architect",
        doj:"2021"
    },
    {
        id:6,
        pic:"images/6.png",
        pname:"Ron",
        role:"Architect",
        doj:"2022"
    },
    {
        id:7,
        pic:"images/7.png",
        pname:"Deiter",
        role:"Architect",
        doj:"2023"
    },
    {
        id:8,
        pic:"images/8.png",
        pname:"Ioana",
        role:"Architect",
        doj:"2024"
    },
    {
        id:9,
        pic:"images/9.png",
        pname:"Klaas",
        role:"Architect",
        doj:"2025"
    },

]